# Make the application available at http://localhost:7070/authserver
server:
  servlet:
    context-path: /authorization-server
  port: 8081 
  
spring: 
  #application:
  #  name: authorization-server

 # cloud:
  #  config:
   #     uri: http://localhost:8888
 
  datasource:
    url: jdbc:mysql://localhost:3306/oauthdb?useSSL=false
    username: root
    password: 
#  tomcat:
#    max-wait: 20000
#    max-active: 50
#    max-idle: 20
#    min-idle: 15
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
       # format_sql: true
      #  id:












message:
    badCredentials: Invalid Credentials
    regError: An account with this email already exists
    regSucc: Registered successfully. Please login
    logout.success: Logged out successfully
NotEmpty: This field is required.
Size: 
  userDto:
     password: Try one with at least 8 characters.
PasswordMatches: 
        user: Password does not match!
