server:
    port: 8082
spring:
 # cloud:
  #  config:
   #      uri: http://localhost:8888
       



# Configure the public key to use for verifying the incoming JWT tokens
  datasource:
    url: jdbc:mysql://localhost:3306/dbboutique_service?useSSL=false
    username: root
    password: 
#  tomcat:
#    max-wait: 20000
#    max-active: 50
#    max-idle: 20
#    min-idle: 15
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
       # format_sql: true
      #  id:


