 # Make the application available at http://localhost:7070/authserver
server:
    port: 8082
spring:
 # cloud:
  #  config:
   #      uri: http://localhost:8888
       



# Configure the public key to use for verifying the incoming JWT tokens
  datasource:
    url: jdbc:mysql://localhost:3306/dbproduct_service?useSSL=false
    username: root
    password: admin123
#  tomcat:
#    max-wait: 20000
#    max-active: 50
#    max-idle: 20
#    min-idle: 15
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
       # format_sql: true
      #  id:

security:
  oauth2:
    client:
      accessTokenUri: http://localhost:8081/oauth/token
      #userAuthorizationUri: http://localhost:7070/authserver/oauth/authorize
      clientId: R2dpxQ3vPrtfgF72
      clientSecret: fDw7Mpkk5czHNuSRtmhGmAGL42CaxQB9
    resource:
     # userInfoUri: http://localhost:9000/user

      jwt:
        keyValue: |
            -----BEGIN PUBLIC KEY-----
            MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhiiifKv6Otf5PyqIE+LQ
            EiJRRh6q8piPY9Okq+RfRu9Bue0D8hq7aFxcgkLZ6Bg9CAS+w1KdaE5MMeOCVVxv
            rpRETzVpAsh6GL5nBc679jSqMzjr3V4uty46ilL4VHKSxlZh5Nmz5EMHPI5iwpNs
            8U5n3QiwsTk514FXad54xPSPH3i/pDzGSZHrVcwDVaOKn7gFiIqP86vkJB47JZv8
            T6P5RK7Rj06zoG45DMGWG3DQv6o1/Jm4IJQWj0AUD3bSHqzXkPr7qyMYvkE4kyMH
            6aVAsAYMxilZFlJMv2b8N883gdi3LEeOJo8zZr5IWyyROfepdeOL7UkAXddAj+dL
            WQIDAQAB
            -----END PUBLIC KEY-----  
            
            
            
            
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true            
            
            
            
            
            
path:
   dirname: ${user.home}/imageProduits/           
            
